/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db;


import fi.jubic.easymapper.jooqtest.chatroom.db.tables.ChatUser;
import fi.jubic.easymapper.jooqtest.chatroom.db.tables.Message;
import fi.jubic.easymapper.jooqtest.chatroom.db.tables.Room;
import fi.jubic.easymapper.jooqtest.chatroom.db.tables.RoomMembership;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>CHAT_SAMPLE</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;
    public static final Index CONSTRAINT_INDEX_6 = Indexes0.CONSTRAINT_INDEX_6;
    public static final Index CONSTRAINT_INDEX_63 = Indexes0.CONSTRAINT_INDEX_63;
    public static final Index PRIMARY_KEY_6 = Indexes0.PRIMARY_KEY_6;
    public static final Index CONSTRAINT_INDEX_2 = Indexes0.CONSTRAINT_INDEX_2;
    public static final Index CONSTRAINT_INDEX_26 = Indexes0.CONSTRAINT_INDEX_26;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index CONSTRAINT_INDEX_7 = Indexes0.CONSTRAINT_INDEX_7;
    public static final Index CONSTRAINT_INDEX_74 = Indexes0.CONSTRAINT_INDEX_74;
    public static final Index PRIMARY_KEY_7 = Indexes0.PRIMARY_KEY_7;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_8 = Internal.createIndex("PRIMARY_KEY_8", ChatUser.CHAT_USER, new OrderField[] { ChatUser.CHAT_USER.ID }, true);
        public static Index CONSTRAINT_INDEX_6 = Internal.createIndex("CONSTRAINT_INDEX_6", Message.MESSAGE, new OrderField[] { Message.MESSAGE.AUTHOR_ID }, false);
        public static Index CONSTRAINT_INDEX_63 = Internal.createIndex("CONSTRAINT_INDEX_63", Message.MESSAGE, new OrderField[] { Message.MESSAGE.ROOM_ID }, false);
        public static Index PRIMARY_KEY_6 = Internal.createIndex("PRIMARY_KEY_6", Message.MESSAGE, new OrderField[] { Message.MESSAGE.ID }, true);
        public static Index CONSTRAINT_INDEX_2 = Internal.createIndex("CONSTRAINT_INDEX_2", Room.ROOM, new OrderField[] { Room.ROOM.ADMINISTRATOR_ID }, false);
        public static Index CONSTRAINT_INDEX_26 = Internal.createIndex("CONSTRAINT_INDEX_26", Room.ROOM, new OrderField[] { Room.ROOM.CREATED_BY_ID }, false);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", Room.ROOM, new OrderField[] { Room.ROOM.ID }, true);
        public static Index CONSTRAINT_INDEX_7 = Internal.createIndex("CONSTRAINT_INDEX_7", RoomMembership.ROOM_MEMBERSHIP, new OrderField[] { RoomMembership.ROOM_MEMBERSHIP.ROOM_ID }, false);
        public static Index CONSTRAINT_INDEX_74 = Internal.createIndex("CONSTRAINT_INDEX_74", RoomMembership.ROOM_MEMBERSHIP, new OrderField[] { RoomMembership.ROOM_MEMBERSHIP.USER_ID }, false);
        public static Index PRIMARY_KEY_7 = Internal.createIndex("PRIMARY_KEY_7", RoomMembership.ROOM_MEMBERSHIP, new OrderField[] { RoomMembership.ROOM_MEMBERSHIP.ID }, true);
    }
}
