/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db;


import fi.jubic.easymapper.jooqtest.chatroom.db.tables.ChatUser;
import fi.jubic.easymapper.jooqtest.chatroom.db.tables.Message;
import fi.jubic.easymapper.jooqtest.chatroom.db.tables.Room;
import fi.jubic.easymapper.jooqtest.chatroom.db.tables.RoomMembership;


/**
 * Convenience access to all tables in CHAT_SAMPLE.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>CHAT_SAMPLE.CHAT_USER</code>.
     */
    public static final ChatUser CHAT_USER = ChatUser.CHAT_USER;

    /**
     * The table <code>CHAT_SAMPLE.MESSAGE</code>.
     */
    public static final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>CHAT_SAMPLE.ROOM</code>.
     */
    public static final Room ROOM = Room.ROOM;

    /**
     * The table <code>CHAT_SAMPLE.ROOM_MEMBERSHIP</code>.
     */
    public static final RoomMembership ROOM_MEMBERSHIP = RoomMembership.ROOM_MEMBERSHIP;
}
