/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db.tables.records;


import fi.jubic.easymapper.jooqtest.chatroom.db.tables.ChatUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatUserRecord extends UpdatableRecordImpl<ChatUserRecord> implements Record4<Integer, String, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CHAT_SAMPLE.CHAT_USER.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>CHAT_SAMPLE.CHAT_USER.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>CHAT_SAMPLE.CHAT_USER.ROLE</code>.
     */
    public void setRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CHAT_SAMPLE.CHAT_USER.ROLE</code>.
     */
    public String getRole() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CHAT_SAMPLE.CHAT_USER.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CHAT_SAMPLE.CHAT_USER.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CHAT_SAMPLE.CHAT_USER.DELETED</code>.
     */
    public void setDeleted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>CHAT_SAMPLE.CHAT_USER.DELETED</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ChatUser.CHAT_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return ChatUser.CHAT_USER.ROLE;
    }

    @Override
    public Field<String> field3() {
        return ChatUser.CHAT_USER.NAME;
    }

    @Override
    public Field<Boolean> field4() {
        return ChatUser.CHAT_USER.DELETED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRole();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Boolean component4() {
        return getDeleted();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRole();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Boolean value4() {
        return getDeleted();
    }

    @Override
    public ChatUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ChatUserRecord value2(String value) {
        setRole(value);
        return this;
    }

    @Override
    public ChatUserRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ChatUserRecord value4(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public ChatUserRecord values(Integer value1, String value2, String value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatUserRecord
     */
    public ChatUserRecord() {
        super(ChatUser.CHAT_USER);
    }

    /**
     * Create a detached, initialised ChatUserRecord
     */
    public ChatUserRecord(Integer id, String role, String name, Boolean deleted) {
        super(ChatUser.CHAT_USER);

        setId(id);
        setRole(role);
        setName(name);
        setDeleted(deleted);
    }
}
