/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db.tables.records;


import fi.jubic.easymapper.jooqtest.chatroom.db.tables.Message;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CHAT_SAMPLE.MESSAGE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>CHAT_SAMPLE.MESSAGE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>CHAT_SAMPLE.MESSAGE.TEXT</code>.
     */
    public void setText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CHAT_SAMPLE.MESSAGE.TEXT</code>.
     */
    public String getText() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CHAT_SAMPLE.MESSAGE.AUTHOR_ID</code>.
     */
    public void setAuthorId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>CHAT_SAMPLE.MESSAGE.AUTHOR_ID</code>.
     */
    public Integer getAuthorId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>CHAT_SAMPLE.MESSAGE.ROOM_ID</code>.
     */
    public void setRoomId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>CHAT_SAMPLE.MESSAGE.ROOM_ID</code>.
     */
    public Integer getRoomId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Message.MESSAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return Message.MESSAGE.TEXT;
    }

    @Override
    public Field<Integer> field3() {
        return Message.MESSAGE.AUTHOR_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Message.MESSAGE.ROOM_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getText();
    }

    @Override
    public Integer component3() {
        return getAuthorId();
    }

    @Override
    public Integer component4() {
        return getRoomId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getText();
    }

    @Override
    public Integer value3() {
        return getAuthorId();
    }

    @Override
    public Integer value4() {
        return getRoomId();
    }

    @Override
    public MessageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MessageRecord value2(String value) {
        setText(value);
        return this;
    }

    @Override
    public MessageRecord value3(Integer value) {
        setAuthorId(value);
        return this;
    }

    @Override
    public MessageRecord value4(Integer value) {
        setRoomId(value);
        return this;
    }

    @Override
    public MessageRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(Integer id, String text, Integer authorId, Integer roomId) {
        super(Message.MESSAGE);

        setId(id);
        setText(text);
        setAuthorId(authorId);
        setRoomId(roomId);
    }
}
