/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db.tables.daos;


import fi.jubic.easymapper.jooqtest.chatroom.db.tables.RoomMembership;
import fi.jubic.easymapper.jooqtest.chatroom.db.tables.records.RoomMembershipRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomMembershipDao extends DAOImpl<RoomMembershipRecord, fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.RoomMembership, Integer> {

    /**
     * Create a new RoomMembershipDao without any configuration
     */
    public RoomMembershipDao() {
        super(RoomMembership.ROOM_MEMBERSHIP, fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.RoomMembership.class);
    }

    /**
     * Create a new RoomMembershipDao with an attached configuration
     */
    public RoomMembershipDao(Configuration configuration) {
        super(RoomMembership.ROOM_MEMBERSHIP, fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.RoomMembership.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.RoomMembership object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.RoomMembership> fetchById(Integer... values) {
        return fetch(RoomMembership.ROOM_MEMBERSHIP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.RoomMembership fetchOneById(Integer value) {
        return fetchOne(RoomMembership.ROOM_MEMBERSHIP.ID, value);
    }

    /**
     * Fetch records that have <code>ROOM_ID IN (values)</code>
     */
    public List<fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.RoomMembership> fetchByRoomId(Integer... values) {
        return fetch(RoomMembership.ROOM_MEMBERSHIP.ROOM_ID, values);
    }

    /**
     * Fetch records that have <code>USER_ID IN (values)</code>
     */
    public List<fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.RoomMembership> fetchByUserId(Integer... values) {
        return fetch(RoomMembership.ROOM_MEMBERSHIP.USER_ID, values);
    }
}
