/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db.tables.daos;


import fi.jubic.easymapper.jooqtest.chatroom.db.tables.Room;
import fi.jubic.easymapper.jooqtest.chatroom.db.tables.records.RoomRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomDao extends DAOImpl<RoomRecord, fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.Room, Integer> {

    /**
     * Create a new RoomDao without any configuration
     */
    public RoomDao() {
        super(Room.ROOM, fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.Room.class);
    }

    /**
     * Create a new RoomDao with an attached configuration
     */
    public RoomDao(Configuration configuration) {
        super(Room.ROOM, fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.Room.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.Room object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.Room> fetchById(Integer... values) {
        return fetch(Room.ROOM.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.Room fetchOneById(Integer value) {
        return fetchOne(Room.ROOM.ID, value);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.Room> fetchByName(String... values) {
        return fetch(Room.ROOM.NAME, values);
    }

    /**
     * Fetch records that have <code>ADMINISTRATOR_ID IN (values)</code>
     */
    public List<fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.Room> fetchByAdministratorId(Integer... values) {
        return fetch(Room.ROOM.ADMINISTRATOR_ID, values);
    }

    /**
     * Fetch records that have <code>CREATED_BY_ID IN (values)</code>
     */
    public List<fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos.Room> fetchByCreatedById(Integer... values) {
        return fetch(Room.ROOM.CREATED_BY_ID, values);
    }
}
