/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db.tables;


import fi.jubic.easymapper.jooqtest.chatroom.db.ChatSample;
import fi.jubic.easymapper.jooqtest.chatroom.db.Indexes;
import fi.jubic.easymapper.jooqtest.chatroom.db.Keys;
import fi.jubic.easymapper.jooqtest.chatroom.db.tables.records.ChatUserRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatUser extends TableImpl<ChatUserRecord> {

    private static final long serialVersionUID = 1518614947;

    /**
     * The reference instance of <code>CHAT_SAMPLE.CHAT_USER</code>
     */
    public static final ChatUser CHAT_USER = new ChatUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChatUserRecord> getRecordType() {
        return ChatUserRecord.class;
    }

    /**
     * The column <code>CHAT_SAMPLE.CHAT_USER.ID</code>.
     */
    public final TableField<ChatUserRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>CHAT_SAMPLE.CHAT_USER.ROLE</code>.
     */
    public final TableField<ChatUserRecord, String> ROLE = createField("ROLE", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CHAT_SAMPLE.CHAT_USER.NAME</code>.
     */
    public final TableField<ChatUserRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>CHAT_SAMPLE.CHAT_USER</code> table reference
     */
    public ChatUser() {
        this(DSL.name("CHAT_USER"), null);
    }

    /**
     * Create an aliased <code>CHAT_SAMPLE.CHAT_USER</code> table reference
     */
    public ChatUser(String alias) {
        this(DSL.name(alias), CHAT_USER);
    }

    /**
     * Create an aliased <code>CHAT_SAMPLE.CHAT_USER</code> table reference
     */
    public ChatUser(Name alias) {
        this(alias, CHAT_USER);
    }

    private ChatUser(Name alias, Table<ChatUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChatUser(Name alias, Table<ChatUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ChatUser(Table<O> child, ForeignKey<O, ChatUserRecord> key) {
        super(child, key, CHAT_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return ChatSample.CHAT_SAMPLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_8);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ChatUserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CHAT_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ChatUserRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ChatUserRecord>> getKeys() {
        return Arrays.<UniqueKey<ChatUserRecord>>asList(Keys.CONSTRAINT_8);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatUser as(String alias) {
        return new ChatUser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatUser as(Name alias) {
        return new ChatUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChatUser rename(String name) {
        return new ChatUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChatUser rename(Name name) {
        return new ChatUser(name, null);
    }
}
