/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db.tables;


import fi.jubic.easymapper.jooqtest.chatroom.db.ChatSample;
import fi.jubic.easymapper.jooqtest.chatroom.db.Keys;
import fi.jubic.easymapper.jooqtest.chatroom.db.tables.records.RoomMembershipRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomMembership extends TableImpl<RoomMembershipRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CHAT_SAMPLE.ROOM_MEMBERSHIP</code>
     */
    public static final RoomMembership ROOM_MEMBERSHIP = new RoomMembership();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomMembershipRecord> getRecordType() {
        return RoomMembershipRecord.class;
    }

    /**
     * The column <code>CHAT_SAMPLE.ROOM_MEMBERSHIP.ID</code>.
     */
    public final TableField<RoomMembershipRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>CHAT_SAMPLE.ROOM_MEMBERSHIP.ROOM_ID</code>.
     */
    public final TableField<RoomMembershipRecord, Integer> ROOM_ID = createField(DSL.name("ROOM_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CHAT_SAMPLE.ROOM_MEMBERSHIP.USER_ID</code>.
     */
    public final TableField<RoomMembershipRecord, Integer> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    private RoomMembership(Name alias, Table<RoomMembershipRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoomMembership(Name alias, Table<RoomMembershipRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>CHAT_SAMPLE.ROOM_MEMBERSHIP</code> table reference
     */
    public RoomMembership(String alias) {
        this(DSL.name(alias), ROOM_MEMBERSHIP);
    }

    /**
     * Create an aliased <code>CHAT_SAMPLE.ROOM_MEMBERSHIP</code> table reference
     */
    public RoomMembership(Name alias) {
        this(alias, ROOM_MEMBERSHIP);
    }

    /**
     * Create a <code>CHAT_SAMPLE.ROOM_MEMBERSHIP</code> table reference
     */
    public RoomMembership() {
        this(DSL.name("ROOM_MEMBERSHIP"), null);
    }

    public <O extends Record> RoomMembership(Table<O> child, ForeignKey<O, RoomMembershipRecord> key) {
        super(child, key, ROOM_MEMBERSHIP);
    }

    @Override
    public Schema getSchema() {
        return ChatSample.CHAT_SAMPLE;
    }

    @Override
    public Identity<RoomMembershipRecord, Integer> getIdentity() {
        return (Identity<RoomMembershipRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RoomMembershipRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_7;
    }

    @Override
    public List<UniqueKey<RoomMembershipRecord>> getKeys() {
        return Arrays.<UniqueKey<RoomMembershipRecord>>asList(Keys.CONSTRAINT_7);
    }

    @Override
    public List<ForeignKey<RoomMembershipRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RoomMembershipRecord, ?>>asList(Keys.CONSTRAINT_74, Keys.CONSTRAINT_747);
    }

    public Room room() {
        return new Room(this, Keys.CONSTRAINT_74);
    }

    public ChatUser chatUser() {
        return new ChatUser(this, Keys.CONSTRAINT_747);
    }

    @Override
    public RoomMembership as(String alias) {
        return new RoomMembership(DSL.name(alias), this);
    }

    @Override
    public RoomMembership as(Name alias) {
        return new RoomMembership(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomMembership rename(String name) {
        return new RoomMembership(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomMembership rename(Name name) {
        return new RoomMembership(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
