/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db.tables;


import fi.jubic.easymapper.jooqtest.chatroom.db.ChatSample;
import fi.jubic.easymapper.jooqtest.chatroom.db.Keys;
import fi.jubic.easymapper.jooqtest.chatroom.db.tables.records.RoomRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Room extends TableImpl<RoomRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CHAT_SAMPLE.ROOM</code>
     */
    public static final Room ROOM = new Room();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomRecord> getRecordType() {
        return RoomRecord.class;
    }

    /**
     * The column <code>CHAT_SAMPLE.ROOM.ID</code>.
     */
    public final TableField<RoomRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>CHAT_SAMPLE.ROOM.NAME</code>.
     */
    public final TableField<RoomRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>CHAT_SAMPLE.ROOM.ADMINISTRATOR_ID</code>.
     */
    public final TableField<RoomRecord, Integer> ADMINISTRATOR_ID = createField(DSL.name("ADMINISTRATOR_ID"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>CHAT_SAMPLE.ROOM.CREATED_BY_ID</code>.
     */
    public final TableField<RoomRecord, Integer> CREATED_BY_ID = createField(DSL.name("CREATED_BY_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    private Room(Name alias, Table<RoomRecord> aliased) {
        this(alias, aliased, null);
    }

    private Room(Name alias, Table<RoomRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>CHAT_SAMPLE.ROOM</code> table reference
     */
    public Room(String alias) {
        this(DSL.name(alias), ROOM);
    }

    /**
     * Create an aliased <code>CHAT_SAMPLE.ROOM</code> table reference
     */
    public Room(Name alias) {
        this(alias, ROOM);
    }

    /**
     * Create a <code>CHAT_SAMPLE.ROOM</code> table reference
     */
    public Room() {
        this(DSL.name("ROOM"), null);
    }

    public <O extends Record> Room(Table<O> child, ForeignKey<O, RoomRecord> key) {
        super(child, key, ROOM);
    }

    @Override
    public Schema getSchema() {
        return ChatSample.CHAT_SAMPLE;
    }

    @Override
    public Identity<RoomRecord, Integer> getIdentity() {
        return (Identity<RoomRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RoomRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_2;
    }

    @Override
    public List<UniqueKey<RoomRecord>> getKeys() {
        return Arrays.<UniqueKey<RoomRecord>>asList(Keys.CONSTRAINT_2);
    }

    @Override
    public List<ForeignKey<RoomRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RoomRecord, ?>>asList(Keys.CONSTRAINT_26, Keys.CONSTRAINT_267);
    }

    public ChatUser constraint_26() {
        return new ChatUser(this, Keys.CONSTRAINT_26);
    }

    public ChatUser constraint_267() {
        return new ChatUser(this, Keys.CONSTRAINT_267);
    }

    @Override
    public Room as(String alias) {
        return new Room(DSL.name(alias), this);
    }

    @Override
    public Room as(Name alias) {
        return new Room(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Room rename(String name) {
        return new Room(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Room rename(Name name) {
        return new Room(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
