/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db.tables;


import fi.jubic.easymapper.jooqtest.chatroom.db.ChatSample;
import fi.jubic.easymapper.jooqtest.chatroom.db.Indexes;
import fi.jubic.easymapper.jooqtest.chatroom.db.Keys;
import fi.jubic.easymapper.jooqtest.chatroom.db.tables.records.RoomMembershipRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomMembership extends TableImpl<RoomMembershipRecord> {

    private static final long serialVersionUID = -1685638934;

    /**
     * The reference instance of <code>CHAT_SAMPLE.ROOM_MEMBERSHIP</code>
     */
    public static final RoomMembership ROOM_MEMBERSHIP = new RoomMembership();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomMembershipRecord> getRecordType() {
        return RoomMembershipRecord.class;
    }

    /**
     * The column <code>CHAT_SAMPLE.ROOM_MEMBERSHIP.ID</code>.
     */
    public final TableField<RoomMembershipRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CHAT_SAMPLE.ROOM_MEMBERSHIP.ROOM_ID</code>.
     */
    public final TableField<RoomMembershipRecord, Integer> ROOM_ID = createField("ROOM_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CHAT_SAMPLE.ROOM_MEMBERSHIP.USER_ID</code>.
     */
    public final TableField<RoomMembershipRecord, Integer> USER_ID = createField("USER_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>CHAT_SAMPLE.ROOM_MEMBERSHIP</code> table reference
     */
    public RoomMembership() {
        this(DSL.name("ROOM_MEMBERSHIP"), null);
    }

    /**
     * Create an aliased <code>CHAT_SAMPLE.ROOM_MEMBERSHIP</code> table reference
     */
    public RoomMembership(String alias) {
        this(DSL.name(alias), ROOM_MEMBERSHIP);
    }

    /**
     * Create an aliased <code>CHAT_SAMPLE.ROOM_MEMBERSHIP</code> table reference
     */
    public RoomMembership(Name alias) {
        this(alias, ROOM_MEMBERSHIP);
    }

    private RoomMembership(Name alias, Table<RoomMembershipRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoomMembership(Name alias, Table<RoomMembershipRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RoomMembership(Table<O> child, ForeignKey<O, RoomMembershipRecord> key) {
        super(child, key, ROOM_MEMBERSHIP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return ChatSample.CHAT_SAMPLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_7, Indexes.CONSTRAINT_INDEX_74, Indexes.PRIMARY_KEY_7);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RoomMembershipRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_7;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RoomMembershipRecord>> getKeys() {
        return Arrays.<UniqueKey<RoomMembershipRecord>>asList(Keys.CONSTRAINT_7);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RoomMembershipRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RoomMembershipRecord, ?>>asList(Keys.CONSTRAINT_74, Keys.CONSTRAINT_747);
    }

    public Room room() {
        return new Room(this, Keys.CONSTRAINT_74);
    }

    public ChatUser chatUser() {
        return new ChatUser(this, Keys.CONSTRAINT_747);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomMembership as(String alias) {
        return new RoomMembership(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomMembership as(Name alias) {
        return new RoomMembership(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomMembership rename(String name) {
        return new RoomMembership(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomMembership rename(Name name) {
        return new RoomMembership(name, null);
    }
}
