/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatUser implements Serializable {

    private static final long serialVersionUID = -650008032;

    private Integer id;
    private String  role;
    private String  name;
    private Boolean deleted;

    public ChatUser() {}

    public ChatUser(ChatUser value) {
        this.id = value.id;
        this.role = value.role;
        this.name = value.name;
        this.deleted = value.deleted;
    }

    public ChatUser(
        Integer id,
        String  role,
        String  name,
        Boolean deleted
    ) {
        this.id = id;
        this.role = role;
        this.name = name;
        this.deleted = deleted;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getDeleted() {
        return this.deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatUser (");

        sb.append(id);
        sb.append(", ").append(role);
        sb.append(", ").append(name);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
