/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message implements Serializable {

    private static final long serialVersionUID = 68732517;

    private Integer id;
    private String  text;
    private Integer authorId;
    private Integer roomId;

    public Message() {}

    public Message(Message value) {
        this.id = value.id;
        this.text = value.text;
        this.authorId = value.authorId;
        this.roomId = value.roomId;
    }

    public Message(
        Integer id,
        String  text,
        Integer authorId,
        Integer roomId
    ) {
        this.id = id;
        this.text = text;
        this.authorId = authorId;
        this.roomId = roomId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Integer getAuthorId() {
        return this.authorId;
    }

    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    public Integer getRoomId() {
        return this.roomId;
    }

    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Message (");

        sb.append(id);
        sb.append(", ").append(text);
        sb.append(", ").append(authorId);
        sb.append(", ").append(roomId);

        sb.append(")");
        return sb.toString();
    }
}
