/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Room implements Serializable {

    private static final long serialVersionUID = -1108106551;

    private Integer id;
    private String  name;
    private Integer administratorId;
    private Integer createdById;

    public Room() {}

    public Room(Room value) {
        this.id = value.id;
        this.name = value.name;
        this.administratorId = value.administratorId;
        this.createdById = value.createdById;
    }

    public Room(
        Integer id,
        String  name,
        Integer administratorId,
        Integer createdById
    ) {
        this.id = id;
        this.name = name;
        this.administratorId = administratorId;
        this.createdById = createdById;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAdministratorId() {
        return this.administratorId;
    }

    public void setAdministratorId(Integer administratorId) {
        this.administratorId = administratorId;
    }

    public Integer getCreatedById() {
        return this.createdById;
    }

    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Room (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(administratorId);
        sb.append(", ").append(createdById);

        sb.append(")");
        return sb.toString();
    }
}
