/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easymapper.jooqtest.chatroom.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomMembership implements Serializable {

    private static final long serialVersionUID = 116207942;

    private Integer id;
    private Integer roomId;
    private Integer userId;

    public RoomMembership() {}

    public RoomMembership(RoomMembership value) {
        this.id = value.id;
        this.roomId = value.roomId;
        this.userId = value.userId;
    }

    public RoomMembership(
        Integer id,
        Integer roomId,
        Integer userId
    ) {
        this.id = id;
        this.roomId = roomId;
        this.userId = userId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getRoomId() {
        return this.roomId;
    }

    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RoomMembership (");

        sb.append(id);
        sb.append(", ").append(roomId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
